'use strict';
// Stub data for `node generator/build.js --sample` — one page of every type,
// shaped EXACTLY like the shards G2–G8 deliver (see README.md "Data contract").
// One locality (Râmeț) is deliberately thin → demonstrates the data-gate demotion.

module.exports = function sampleData() {
  return {
    counties: [
      {
        slug: 'alba', name: 'Alba',
        ocpiHq: 'OCPI Alba — Alba Iulia, str. Septimius Severus nr. 59',
        bcpiOffices: ['Alba Iulia', 'Aiud', 'Blaj', 'Câmpeni', 'Sebeș'],
        countyNote: 'În județul Alba, dosarele de cadastru se repartizează pe birouri teritoriale (BCPI) în funcție de localitatea imobilului, nu de domiciliul proprietarului. Pentru zonele care au trecut prin înregistrarea sistematică, verificăm întâi dacă imobilul are deja număr cadastral atribuit din oficiu.',
        feeNote: 'Tarifele ANCPI sunt aceleași în tot județul; diferă doar termenele de soluționare de la un birou la altul.',
      },
      {
        slug: 'mures', name: 'Mureș',
        ocpiHq: 'OCPI Mureș — Târgu Mureș, str. Căprioarei nr. 2',
        bcpiOffices: ['Târgu Mureș', 'Luduș', 'Reghin', 'Sighișoara', 'Târnăveni'],
        countyNote: 'Pentru imobilele din județul Mureș, competența aparține biroului teritorial în raza căruia se află imobilul; pentru zona Luduș–Iernut, dosarele se depun la BCPI Luduș.',
        feeNote: 'Deplasarea în județul Mureș se calculează în funcție de distanță.',
      },
    ],
    localities: [
      {
        name: 'Lopadea Nouă', slug: 'lopadea-noua', county: 'Alba', countySlug: 'alba',
        type: 'comună', villages: ['Lopadea Nouă', 'Asinip', 'Băgău', 'Beța', 'Cicârd', 'Ciuguzel', 'Ocnișoara', 'Odverem'],
        lat: 46.3592, lon: 23.8148, matrix: 'full', profile: 'campie',
        ocpiOffice: { name: 'BCPI Aiud', address: 'str. Unirii nr. 8, Aiud' },
        localNote: 'În Lopadea Nouă cererile vin cel mai des pentru terenuri agricole moștenite, multe cu titluri de proprietate eliberate în anii ’90 și nemăsurate vreodată. Zona viticolă dinspre Băgău are parcele lungi și înguste, unde limitele reale diferă frecvent de schițele vechi, iar vecinii trebuie convocați la măsurătoare.',
        nearby: [],
      },
      {
        name: 'Teiuș', slug: 'teius', county: 'Alba', countySlug: 'alba',
        type: 'oraș', villages: ['Teiuș', 'Beldiu', 'Căpud', 'Coșlariu Nou', 'Pețelca'],
        lat: 46.2011, lon: 23.6815, matrix: 'full', profile: 'urban',
        ocpiOffice: { name: 'BCPI Alba Iulia', address: 'str. Septimius Severus nr. 59, Alba Iulia' },
        localNote: 'Teiușul este nod feroviar, iar multe imobile din intravilan au fost afectate de exproprieri și modernizări ale infrastructurii — verificăm de fiecare dată suprapunerile cu coridorul căii ferate înainte de depunere. În ultimii ani am lucrat aici frecvent la intabulări de case cumpărate prin credite ipotecare, unde banca cere carte funciară la zi.',
        nearby: [],
      },
      {
        name: 'Sânpaul', slug: 'sanpaul', county: 'Mureș', countySlug: 'mures',
        type: 'comună', villages: ['Sânpaul', 'Chirileu', 'Dileu Nou', 'Sânmărghita', 'Valea Izvoarelor'],
        lat: 46.4652, lon: 24.3729, matrix: 'reduced', profile: 'campie',
        ocpiOffice: { name: 'BCPI Luduș', address: 'str. Republicii nr. 27, Luduș' },
        localNote: 'La Sânpaul lucrăm mai ales pentru hale și platforme din zona industrială dezvoltată pe lunca Mureșului, unde investitorii au nevoie de planuri topografice de detaliu și de trasări precise ale fundațiilor. Terenurile din luncă cer atenție la cotele de nivel — le măsurăm și le predăm în sistem de referință Marea Neagră 1975.',
        nearby: [],
      },
      {
        // deliberately thin: no villages, no ocpiOffice, no localNote → data gate demotes it
        name: 'Râmeț', slug: 'ramet', county: 'Alba', countySlug: 'alba',
        type: 'comună', villages: [], lat: 46.3033, lon: 23.5262, matrix: 'full', profile: 'montan',
        localNote: '', nearby: [],
      },
    ],
    services: [
      {
        name: 'Intabulare teren', slug: 'intabulare-teren', shortName: 'intabulare teren',
        tier2Available: false, hubOnly: false,
        metaDescription: 'Intabulare teren intravilan sau extravilan: acte necesare, pași, prețuri orientative. Topograf autorizat ANCPI, județul Alba.',
        hubIntro: 'Intabularea terenului înseamnă înscrierea lui în cartea funciară, cu măsurătoare la fața locului, plan de amplasament și delimitare și dosar depus la OCPI. Fără intabulare, terenul nu poate fi vândut, ipotecat sau dezmembrat legal.',
        introVariants: [
          { profile: 'campie', text: 'Ai un teren agricol în {localitate} pe care vrei să-l vinzi, să-l arendezi cu acte în regulă sau să-l lași moștenire fără complicații? Intabularea este primul pas: măsurăm parcela cu echipament GPS de precizie, întocmim planul de amplasament și delimitare și depunem dosarul complet la {ocpi}.' },
          { profile: 'campie', text: 'În zonele agricole precum {localitate}, multe terenuri au titlu de proprietate din anii ’90 dar nu au fost niciodată măsurate și înscrise în cartea funciară. Ne ocupăm de tot procesul: identificarea parcelei în teren, măsurătoarea, vecinătățile și depunerea documentației la {ocpi}.' },
          { profile: 'montan', text: 'Terenurile din zona montană, cum sunt cele din {localitate}, au adesea limite naturale — pâraie, culmi, drumuri forestiere — care nu corespund cu schițele vechi. Măsurăm parcela la fața locului, lămurim vecinătățile și pregătim dosarul de intabulare pentru {ocpi}.' },
          { profile: 'urban', text: 'Pentru terenurile din intravilanul localității {localitate}, intabularea corectă este condiția oricărei tranzacții sau autorizații de construire. Verificăm situația juridică, măsurăm terenul și depunem documentația cadastrală la {ocpi}.' },
          { profile: 'periurban', text: 'În zonele aflate în extinderea orașelor, precum {localitate}, terenurile trecute din extravilan în intravilan au nevoie de documentație cadastrală adusă la zi înainte de vânzare sau construire. Ne ocupăm de măsurătoare, de actualizarea categoriei de folosință și de dosarul pentru {ocpi}.' },
          { profile: 'urban', text: 'Vinzi sau cumperi un teren în {localitate}? Notarul va cere extras de carte funciară valabil, iar dacă terenul nu este intabulat, tranzacția se blochează. Facem măsurătoarea, planul de amplasament și delimitare și depunem dosarul la {ocpi}, ca să semnezi la termen.' },
        ],
        process: [
          'Discutăm situația pe WhatsApp sau la telefon și stabilim actele de pornire.',
          'Măsurăm terenul la fața locului cu echipament GPS/stație totală.',
          'Întocmim planul de amplasament și delimitare (PAD) și restul documentației.',
          'Depunem dosarul la biroul de cadastru competent și urmărim soluționarea.',
          'Primești extrasul de carte funciară cu terenul înscris pe numele tău.',
        ],
        documents: [
          'Act de proprietate (titlu de proprietate, contract, certificat de moștenitor)',
          'Act de identitate proprietar(i)',
          'Certificat fiscal de la primărie, pentru cadastru',
          'Extras de carte funciară pentru informare (dacă există)',
          'Adeverință de la registrul agricol, unde este cazul',
        ],
        priceRange: '900–2.500 lei, în funcție de suprafață și acte',
        faqPool: [
          { q: 'Cât durează intabularea unui teren în {localitate}?', a: 'De regulă 30–45 de zile de la depunerea dosarului complet la {ocpi}, la care se adaugă timpul de măsurătoare și de obținere a actelor de la primărie. Termenul legal de soluționare poate fi redus contra unei taxe de urgență.' },
          { q: 'Pot intabula un teren moștenit dacă succesiunea nu este făcută?', a: 'Nu direct — mai întâi se dezbate succesiunea la notar, apoi certificatul de moștenitor devine actul de proprietate pe baza căruia facem documentația cadastrală. Vă putem recomanda pașii exacți pentru situația dumneavoastră.' },
          { q: 'Ce se întâmplă dacă vecinii nu sunt de acord cu limita?', a: 'La măsurătoare convocăm vecinii pentru semnarea procesului-verbal de vecinătate. Dacă există divergențe, le documentăm și vă explicăm variantele: mediere, expertiză sau acțiune în instanță pentru grănițuire.' },
          { q: 'Terenul din {localitate} apare la registrul agricol, dar nu are carte funciară. E o problemă?', a: 'Este exact situația pe care o rezolvă intabularea: registrul agricol dovedește folosința, dar numai înscrierea în cartea funciară vă face proprietar tabular, cu drept deplin de vânzare sau ipotecare.' },
          { q: 'Cât costă intabularea unui teren agricol?', a: 'Onorariul depinde de suprafață, de numărul de parcele și de actele existente — de regulă între 900 și 2.500 lei, la care se adaugă tarifele ANCPI. După o discuție scurtă pe WhatsApp vă dăm un preț ferm.' },
          { q: 'Trebuie să fiu prezent la măsurătoare?', a: 'Este recomandat — dumneavoastră sau cineva care cunoaște limitele terenului. Pentru clienții plecați din țară putem lucra cu un împuternicit sau cu un vecin care indică limitele, iar actele se semnează electronic sau prin poștă.' },
          { q: 'Terenul are suprafață diferită în acte față de teren. Ce facem?', a: 'Situația este frecventă la titlurile vechi. În funcție de diferență, legea permite înscrierea suprafeței măsurate cu acordul vecinilor sau impune rectificarea actelor. Vă spunem exact varianta aplicabilă după măsurătoare.' },
          { q: 'Faceți și dezmembrarea dacă vreau să vând doar o parte din teren?', a: 'Da — după intabulare putem dezmembra parcela în loturi, cu documentație cadastrală separată pentru fiecare lot și înscriere în cărți funciare noi.' },
        ],
        related: ['plan-topografic'],
      },
      {
        name: 'Plan topografic', slug: 'plan-topografic', shortName: 'plan topografic',
        tier2Available: true, hubOnly: false,
        metaDescription: 'Plan topografic pentru autorizație de construire, PUZ/PUD sau proiectare: măsurători precise, avizat OCPI. Topograf autorizat ANCPI.',
        hubIntro: 'Planul topografic este piesa de bază a oricărui proiect de construire: redă fidel terenul — cote, construcții, rețele, drumuri — și stă la baza certificatului de urbanism, a autorizației de construire și a proiectării.',
        introVariants: [
          { profile: 'campie', text: 'Construiești sau extinzi în {localitate}? Realizăm planul topografic necesar autorizației de construire, cu ridicarea completă a terenului și predare în format acceptat de primărie și de proiectant.' },
          { profile: 'campie', text: 'Pentru proiectele din {localitate} — de la locuințe la hale agricole — întocmim planuri topografice cu toate detaliile cerute de proiectant: cote de nivel, vecinătăți, rețele vizibile și acces.' },
          { profile: 'montan', text: 'Pe terenurile în pantă din zona {localitate}, planul topografic cu curbe de nivel corecte face diferența între un proiect realist și unul care se scumpește la execuție. Măsurăm cu stație totală și GPS, indiferent de teren.' },
          { profile: 'urban', text: 'Pentru autorizații de construire în {localitate}, primăria cere plan topografic vizat OCPI. Îl întocmim complet — ridicare, cote, vecinătăți, încadrare în zonă — și îl predăm gata de depus.' },
          { profile: 'periurban', text: 'Loturile noi din jurul localității {localitate} au nevoie de planuri topografice atât pentru urbanism (PUZ/PUD), cât și pentru branșamente și drumuri de acces. Livrăm măsurători pe care proiectanții pot construi direct.' },
          { profile: 'urban', text: 'Un plan topografic corect scurtează avizarea: cuprinde cotele, construcțiile existente, împrejmuirile și rețelele vizibile din {localitate}, exact în formatul cerut de OCPI și de arhitect.' },
        ],
        process: [
          'Stabilim scopul planului (autorizare, proiectare, PUZ/PUD) și zona de măsurat.',
          'Facem ridicarea topografică la fața locului.',
          'Întocmim planul în format digital și analogic, cu inventar de coordonate.',
          'Obținem avizul OCPI atunci când este cerut prin certificatul de urbanism.',
        ],
        documents: [
          'Extras de carte funciară (dacă imobilul este intabulat)',
          'Certificat de urbanism, dacă a fost emis',
          'Planuri sau proiecte existente ale amplasamentului, dacă există',
        ],
        priceRange: '700–1.800 lei, în funcție de suprafață și de detaliile cerute',
        faqPool: [
          { q: 'Pentru ce am nevoie de plan topografic în {localitate}?', a: 'Cel mai des pentru autorizația de construire — primăria îl cere prin certificatul de urbanism — dar și pentru proiectare, PUZ/PUD, branșamente sau calculul volumelor de terasamente.' },
          { q: 'Planul topografic trebuie avizat de OCPI?', a: 'Dacă certificatul de urbanism cere „plan topografic vizat OCPI", da — ne ocupăm noi de obținerea avizului. Pentru uz intern de proiectare, avizul nu este obligatoriu.' },
          { q: 'În cât timp este gata planul topografic?', a: 'Măsurătoarea durează de obicei o singură zi; predarea planului, 3–7 zile lucrătoare, plus termenul OCPI dacă este necesară avizarea.' },
          { q: 'Ce diferență este între planul topografic și cel cadastral?', a: 'Planul cadastral delimitează proprietatea pentru cartea funciară; planul topografic redă terenul cu toate detaliile — cote, construcții, rețele — pentru proiectare și autorizare. Sunt documente diferite, cu scopuri diferite.' },
          { q: 'Măsurați și terenuri în pantă sau greu accesibile?', a: 'Da — folosim stație totală și GPS geodezic, iar pentru zonele acoperite sau abrupte combinăm metodele astfel încât precizia să nu aibă de suferit.' },
          { q: 'Predați planul și în format digital pentru proiectant?', a: 'Da — livrăm DWG/DXF cu inventar de coordonate în sistemul Stereo 70, plus PDF și exemplare tipărite, după nevoile proiectantului.' },
        ],
        related: ['intabulare-teren'],
      },
    ],
    guides: [
      {
        slug: 'preturi-cadastru-intabulare',
        title: 'Prețuri cadastru și intabulare 2026 — ghid orientativ',
        metaDescription: 'Cât costă cadastrul și intabularea în 2026: intervale orientative pe tipuri de lucrări, taxe ANCPI și ce influențează prețul final.',
        h1: 'Cât costă cadastrul și intabularea în 2026?',
        whatsappTopic: 'prețurile pentru cadastru și intabulare',
        sections: [
          { type: 'html', heading: 'De ce „interval orientativ" și nu preț fix', html: '<p>Două terenuri de aceeași suprafață pot cere volume de muncă foarte diferite: unul are acte clare și vecini intabulați, celălalt are titlu din 1993, suprafață diferită în teren și moștenitori în trei țări. De aceea prezentăm intervale reale, nu prețuri fixe — iar după o discuție scurtă pe WhatsApp primiți un preț ferm pentru situația dumneavoastră.</p>' },
          { type: 'table', heading: 'Intervale orientative pe tipuri de lucrări', head: ['Lucrare', 'Interval orientativ'], rows: [['Cadastru + intabulare apartament', '500–900 lei'], ['Cadastru + intabulare casă + teren', '1.100–2.800 lei'], ['Intabulare teren extravilan', '900–2.500 lei'], ['Plan topografic pentru autorizație', '700–1.800 lei'], ['Dezmembrare (2–3 loturi)', '1.200–2.600 lei']] },
          { type: 'checklist', heading: 'Ce influențează prețul final', items: ['Suprafața și forma terenului', 'Numărul de parcele și de proprietari', 'Actele existente și vechimea lor', 'Distanța față de birou și accesul în teren', 'Regimul de urgență cerut la OCPI'] },
          { type: 'faq', items: [
            { q: 'Taxele ANCPI sunt incluse în onorariu?', a: 'Le evidențiem separat, ca să vedeți exact cât costă serviciul și cât reprezintă taxele oficiale. Tariful ANCPI pentru intabulare obișnuită este public și același pentru toți.' },
            { q: 'Plata se face la început sau la final?', a: 'De regulă un avans la începerea lucrării și restul la predare. Pentru lucrări mari stabilim etape clare de la început.' },
          ] },
        ],
        related: [],
      },
    ],
    fonduri: [
      {
        slug: 'teren-neintabulat-fonduri-europene',
        title: 'Teren neintabulat și fonduri europene — ce faci înainte de depunere',
        metaDescription: 'Terenul fără carte funciară blochează eligibilitatea proiectelor cu fonduri europene. Pașii reali și termenele pentru intabulare înainte de depunere.',
        h1: 'Teren neintabulat? Ce faci înainte să depui proiectul',
        whatsappTopic: 'un teren neintabulat pentru un proiect cu finanțare',
        hook: 'deadline',
        sections: [
          { type: 'html', heading: 'De ce cere finanțatorul carte funciară', html: '<p>Aproape toate ghidurile solicitantului — PNRR, AFIR, POR — cer dovada dreptului asupra terenului: extras de carte funciară recent, fără sarcini care să afecteze investiția. Un teren neintabulat nu poate produce acest document, deci dosarul pică la eligibilitate înainte de a fi evaluat.</p>' },
          { type: 'table', heading: 'Termene realiste', head: ['Etapă', 'Durată tipică'], rows: [['Măsurătoare + documentație cadastrală', '1–2 săptămâni'], ['Soluționare OCPI (regim normal)', '3–5 săptămâni'], ['Soluționare OCPI (regim de urgență)', '1–2 săptămâni'], ['Total realist până la extras CF', '4–7 săptămâni']] },
          { type: 'html', heading: 'Planificarea inversă, de la termenul de depunere', html: '<p>Lucrăm invers: de la data limită a apelului scădem termenele OCPI și de măsurătoare și vă spunem sincer dacă intrarea în termen este realistă. Dacă nu este, vă spunem la fel de sincer — înainte să cheltuiți pe consultanță.</p>' },
        ],
        related: [],
      },
    ],
    solar: [
      {
        slug: 'due-diligence-teren-parc-fotovoltaic',
        title: 'Due diligence de teren pentru parcuri fotovoltaice',
        metaDescription: 'Verificarea topografică și cadastrală a terenului înainte de a cumpăra sau închiria pentru un parc fotovoltaic: suprapuneri, sarcini, accese, cote.',
        h1: 'Due diligence de teren pentru un parc fotovoltaic',
        whatsappTopic: 'o verificare de teren pentru un parc fotovoltaic',
        hook: 'epc',
        sections: [
          { type: 'html', heading: 'Ce verificăm înainte să semnați', html: '<p>O verificare topografică preliminară costă o fracțiune dintr-o afacere proastă cu terenul. Confirmăm limitele reale față de cartea funciară, căutăm suprapuneri cu parcelele vecine, verificăm accesul legal la drum și cotele de nivel care influențează proiectarea structurii.</p>' },
          { type: 'checklist', heading: 'Livrabilele verificării', items: ['Raport de suprapunere cadastrală', 'Măsurătoare de contur cu GPS geodezic', 'Verificarea acceselor și a servituților vizibile', 'Model de teren pentru estimarea pantelor', 'Recomandări pentru pașii cadastrali următori'] },
        ],
        related: [],
      },
    ],
    dictionary: [
      {
        term: 'Carte funciară', slug: 'carte-funciara',
        gloss: 'Registrul public în care se înscriu proprietatea și celelalte drepturi asupra unui imobil.',
        definition: 'Cartea funciară este registrul public, ținut de oficiile de cadastru (OCPI), în care se înscrie situația juridică a fiecărui imobil: cine este proprietarul, cum a dobândit imobilul, ce suprafață și ce număr cadastral are, precum și eventualele sarcini — ipoteci, servituți, interdicții. Ea are trei părți: foaia A descrie imobilul, foaia B arată proprietarii, iar foaia C cuprinde sarcinile. Orice vânzare, moștenire sau ipotecă se bazează pe informațiile din cartea funciară, iar notarul cere întotdeauna un extras recent. Dacă un teren sau o casă nu are carte funciară deschisă, imobilul trebuie mai întâi intabulat, adică măsurat de un topograf autorizat și înscris la OCPI pe baza actelor de proprietate.',
        example: 'Înainte de a semna antecontractul, cumpărătorul a cerut extrasul de carte funciară și a văzut la foaia C o ipotecă neradiată.',
        related: ['intabulare', 'extras-de-carte-funciara'],
        ctaService: 'cadastru-si-intabulare',
      },
      {
        term: 'Intabulare', slug: 'intabulare',
        gloss: 'Înscrierea definitivă a dreptului de proprietate în cartea funciară.',
        definition: 'Intabularea este operațiunea prin care dreptul de proprietate — sau un alt drept real, cum ar fi ipoteca — se înscrie definitiv în cartea funciară. Practic, după ce un topograf autorizat măsoară imobilul și întocmește documentația cadastrală, dosarul se depune la OCPI, imobilul primește număr cadastral, iar proprietarul este trecut în foaia B a cărții funciare. Din acel moment dreptul lui este opozabil oricui: poate vinde, ipoteca sau dezmembra imobilul. Fără intabulare, chiar dacă există acte vechi de proprietate, tranzacțiile notariale nu se pot încheia, iar imobilul nu poate fi adus garanție la bancă. Termenul de soluționare obișnuit la OCPI este de câteva săptămâni și poate fi scurtat cu taxă de urgență.',
        example: 'După dezbaterea succesiunii, moștenitorii au făcut intabularea terenului ca să îl poată vinde.',
        related: ['carte-funciara', 'numar-cadastral'],
        ctaService: 'intabulare-teren',
      },
      {
        term: 'Extras de carte funciară', slug: 'extras-de-carte-funciara',
        gloss: 'Documentul oficial care arată situația la zi a unui imobil din cartea funciară.',
        definition: 'Extrasul de carte funciară este documentul oficial eliberat de OCPI care fotografiază situația juridică a unui imobil la momentul emiterii: descrierea imobilului, proprietarii și sarcinile existente. Există două tipuri: extrasul pentru informare, pe care îl poate cere oricine și care are rol de verificare, și extrasul pentru autentificare, cerut de notar la semnarea unui act de vânzare sau de ipotecă — acesta blochează cartea funciară pentru zece zile lucrătoare, ca nimeni altcineva să nu poată înscrie ceva în acest interval. Extrasul se obține online sau la ghișeu, iar valabilitatea practică este scurtă: băncile și notarii cer de regulă un document de maximum 30 de zile.',
        example: 'Banca a cerut un extras de carte funciară nu mai vechi de 30 de zile înainte de aprobarea creditului ipotecar.',
        related: ['carte-funciara', 'intabulare'],
        ctaService: 'servicii-ocpi',
      },
      {
        term: 'Număr cadastral', slug: 'numar-cadastral',
        gloss: 'Identificatorul unic pe care îl primește un imobil la înscrierea în sistemul de cadastru.',
        definition: 'Numărul cadastral este identificatorul unic atribuit unui imobil — teren, cu sau fără construcții — atunci când este înscris în sistemul integrat de cadastru și carte funciară. El leagă măsurătoarea din teren, adică geometria parcelei cu coordonatele ei, de situația juridică din cartea funciară. Două imobile nu pot avea același număr cadastral, iar orice modificare — dezmembrare, alipire, construcție nouă — generează documentație cadastrală care actualizează sau creează numere noi. Când cineva spune că un teren „are cadastru", înseamnă de fapt că are număr cadastral și geometrie recepționată de OCPI. Numărul cadastral nu trebuie confundat cu numărul topografic vechi din sistemele de evidență anterioare, folosit încă în unele zone din Transilvania.',
        example: 'La dezmembrare, parcela inițială s-a închis, iar cele trei loturi noi au primit numere cadastrale separate.',
        related: ['carte-funciara', 'intabulare'],
        ctaService: 'cadastru-si-intabulare',
      },
    ],
    english: [
      {
        path: '/en/index.html',
        title: 'Land Surveying & Cadastral Services in Romania | Fleser Aurel Expert',
        metaDescription: 'ANCPI-licensed land surveyor in Alba county, Romania: cadastral registration, topographic surveys, land due diligence for investors. 25+ years, 1052+ projects.',
        h1: 'Land surveying and cadastral services in Romania',
        navLabel: 'Home',
        whatsappPrefillEn: 'Hello! I need land surveying services in Romania.',
        roPair: '/',
        sections: [
          { type: 'html', heading: 'Who we are', html: '<p>Fleser Aurel Expert is an ANCPI-licensed land surveying practice based in Aiud, Alba county — the heart of Transylvania. Over 25 years we have completed more than 1,052 projects: cadastral registrations, topographic surveys, boundary stakeouts and land due diligence for private owners, developers and investors.</p>' },
          { type: 'html', heading: 'How we work with international clients', html: '<p>WhatsApp is our default channel: describe your project, attach the land-book extract, and you will get a clear answer about feasibility, timeline and cost. Documents can be signed remotely through a proxy — many of our clients live abroad.</p>' },
        ],
        related: [],
      },
      {
        path: '/en/services/topographic-survey.html',
        title: 'Topographic Survey in Romania — Licensed Surveyor | Fleser Aurel Expert',
        metaDescription: 'Topographic surveys for building permits, design and development projects in Alba county and central Romania. ANCPI-licensed, fast delivery, DWG/DXF output.',
        h1: 'Topographic survey in Romania',
        navLabel: 'Topographic survey',
        whatsappPrefillEn: 'Hello! I need a topographic survey in Romania for my project.',
        roPair: '/servicii/plan-topografic/index.html',
        sections: [
          { type: 'html', heading: 'What you get', html: '<p>A topographic survey maps the terrain in full detail — elevations, existing structures, visible utilities, access roads — in the Romanian Stereo 70 coordinate system. It is the mandatory basis for building permits (autorizație de construire) and the starting point of any serious design work.</p>' },
          { type: 'checklist', heading: 'Deliverables', items: ['Field survey with GNSS + total station', 'DWG/DXF drawing with coordinate inventory', 'PDF and printed copies for the permit file', 'OCPI endorsement where required'] },
        ],
        related: ['/en/index.html'],
      },
    ],
    hreflang: [],
  };
};
